// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEtS6QaXqJwmR31bHXmwgsDfSy0kde56A',
    appId: '1:592728070584:web:6237a595908e9e3f62974d',
    messagingSenderId: '592728070584',
    projectId: 'automarket-a4c48',
    authDomain: 'automarket-a4c48.firebaseapp.com',
    storageBucket: 'automarket-a4c48.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBigCqCUrVxsuhOF8fo5g3pLtcKp8Pt1Ig',
    appId: '1:592728070584:android:1444c4d135f21ecd62974d',
    messagingSenderId: '592728070584',
    projectId: 'automarket-a4c48',
    storageBucket: 'automarket-a4c48.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdkSILT7O3lPaFldvlMwEYxz9-EzuiGvE',
    appId: '1:592728070584:ios:8bda04b99e3f4e7062974d',
    messagingSenderId: '592728070584',
    projectId: 'automarket-a4c48',
    storageBucket: 'automarket-a4c48.appspot.com',
    iosBundleId: 'com.example.flutterApplicationautomarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdkSILT7O3lPaFldvlMwEYxz9-EzuiGvE',
    appId: '1:592728070584:ios:8bda04b99e3f4e7062974d',
    messagingSenderId: '592728070584',
    projectId: 'automarket-a4c48',
    storageBucket: 'automarket-a4c48.appspot.com',
    iosBundleId: 'com.example.flutterApplicationautomarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEtS6QaXqJwmR31bHXmwgsDfSy0kde56A',
    appId: '1:592728070584:web:803469113fd189e862974d',
    messagingSenderId: '592728070584',
    projectId: 'automarket-a4c48',
    authDomain: 'automarket-a4c48.firebaseapp.com',
    storageBucket: 'automarket-a4c48.appspot.com',
  );
}
